name: adaptive-docs

channels:
  - conda-forge

dependencies:
  - python
  - sortedcollections
  - scikit-optimize
  - cloudpickle
  - loky
  - scikit-learn
  - scipy
  - holoviews
  - bokeh
  - panel
  - plotly
  - ipywidgets
  - jupyter-sphinx
  - atomicwrites
  - sphinx_fontawesome
  - sphinx
  - m2r2
  - sphinx_rtd_theme
  - ffmpeg
