name: adaptive-docs

channels:
  - conda-forge

dependencies:
  - python
  - sortedcollections=2.1.0
  - scikit-optimize=0.8.1
  - scikit-learn=0.24.2
  - scipy=1.9.1
  - holoviews=1.14.6
  - bokeh=2.4.0
  - panel=0.12.7
  - plotly=5.3.1
  - ipywidgets=7.6.5
  - jupyter-sphinx=0.4.0
  - sphinx_fontawesome=0.0.6
  - sphinx=4.2.0
  - sphinx_rtd_theme=1.0.0
  - ffmpeg=4.3.2
  - cloudpickle
  - loky
  - myst-parser
